apiVersion: v1
kind: Secret
metadata:
  name: mongodb-credentials
stringData:
  MONGODB_USERNAME: admin
  MONGODB_PASSWORD: secret
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
  MONGODB_HOST: mongodb-service
  MONGODB_DB: test-app
  MONGODB_COLLECTION: data
  STRING: String that is saved in DB and served by webserver
