apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  selector:
    app: db
  ports:
    - port: 27017
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
spec:
  resources:
    requests:
      storage: 512Mi
  accessModes:
    - ReadWriteOnce
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: db
spec:
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - image: weibeld/test-db
          name: mongodb
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: db-data
              mountPath: /data/db
          env:
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: DB_NAME
            - name: DB_COLLECTION
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: DB_COLLECTION
            - name: DB_STRING
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: DB_STRING
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: db-pvc
