apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    app: mongodb
  ports:
    - port: 27017
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
spec:
  resources:
    requests:
      storage: 512Mi
  accessModes:
    - ReadWriteOnce
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongodb
spec:
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      volumes:
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: mongodb-pvc
      containers:
        - image: weibeld/test-mongodb
          name: mongodb
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
          env:
            - name: MONGODB_DB
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: MONGODB_DB
            - name: MONGODB_COLLECTION
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: MONGODB_COLLECTION
            - name: STRING
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: STRING
            # https://github.com/docker-library/docs/blob/master/mongo/README.md#mongo_initdb_root_username-mongo_initdb_root_password
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-credentials
                  key: MONGODB_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-credentials
                  key: MONGODB_PASSWORD
