apiVersion: v1
kind: Service
metadata:
  name: webserver-service
spec:
  type: LoadBalancer
  selector:
    app: webserver
  ports:
    - port: 8080
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webserver
spec:
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
        - image: weibeld/test-webserver
          name: webserver
          ports:
            - containerPort: 8080
          env:
            - name: MONGODB_HOST
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: MONGODB_HOST
            - name: MONGODB_DB
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: MONGODB_DB
            - name: MONGODB_COLLECTION
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: MONGODB_COLLECTION
            - name: MONGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-credentials
                  key: MONGODB_USERNAME
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-credentials
                  key: MONGODB_PASSWORD
