apiVersion: v1
kind: Service
metadata:
  name: webserver-service
spec:
  type: LoadBalancer
  selector:
    app: webserver
  ports:
    - port: 8080
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webserver
spec:
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
        - image: weibeld/test-webserver
          name: webserver
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: DB_HOST
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: DB_NAME
            - name: DB_COLLECTION
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: DB_COLLECTION
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_PASSWORD
